---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30030
    name: external
  selector:
    app: grafana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "grafana"
  labels:
    app: "grafana"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "grafana"
        name: "grafana"
        app: "grafana"
    spec:
      containers:
        - name: "grafana"
          image: "balon/docker-grafana"
          ports:
            - containerPort: 3000
          env:
            - name: INFLUXDB_SERVICE_URL
              value: http://influxdb:8086
            - name: GRAFANA_PORT
              value: "3000"
              # The following env variables are required to make Grafana accessible via
              # the kubernetes api-server proxy. On production clusters, we recommend
              # removing these env variables, setup auth for grafana, and expose the grafana
              # service using a LoadBalancer or a public IP.
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_DASHBOARDS_JSON_ENABLED
              value: "true"
            - name: GF_DASHBOARDS_JSON_PATH
              value: "/dashboards"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: "/dashboards"
              name: dashboards-volume
      volumes:
        - configMap:
            name: grafana-dashboards
          name: dashboards-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  test-dashboard.json: |
    {
      "__requires": [
        {
          "type": "panel",
          "id": "graph",
          "name": "Graph",
          "version": ""
        },
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "4.0.2"
        },
        {
          "type": "datasource",
          "id": "influxdb-datasource",
          "name": "InfluxDB",
          "version": "1.0.0"
        }
      ],
      "id": null,
      "title": "Test dashboard",
      "tags": [],
      "style": "dark",
      "timezone": "browser",
      "editable": true,
      "sharedCrosshair": false,
      "hideControls": false,
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "templating": {
        "list": []
      },
      "annotations": {
        "list": []
      },
      "refresh": "10s",
      "schemaVersion": 13,
      "version": 1,
      "links": [],
      "gnetId": null,
      "rows": [
        {
          "title": "Dashboard Row",
          "panels": [
            {
              "aliasColors": {},
              "bars": false,
              "datasource": "influxdb-datasource",
              "editable": true,
              "error": false,
              "fill": 1,
              "id": 1,
              "interval": "",
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": true,
                "total": false,
                "values": false
              },
              "lines": true,
              "linewidth": 1,
              "links": [],
              "nullPointMode": "connected",
              "percentage": false,
              "pointradius": 5,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "span": 12,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "alias": "",
                  "dsType": "influxdb",
                  "groupBy": [
                    {
                      "params": [
                        "instance"
                      ],
                      "type": "tag"
                    }
                  ],
                  "hide": false,
                  "measurement": "scrape_duration_seconds",
                  "policy": "autogen",
                  "query": "SELECT mean(\"value\") FROM \"autogen\".\"up\" WHERE $timeFilter GROUP BY time($interval), \"instance\"",
                  "rawQuery": false,
                  "refId": "A",
                  "resultFormat": "time_series",
                  "select": [
                    [
                      {
                        "params": [
                          "value"
                        ],
                        "type": "field"
                      }
                    ]
                  ],
                  "tags": []
                }
              ],
              "thresholds": [],
              "timeFrom": null,
              "timeShift": null,
              "title": "Panel Title",
              "tooltip": {
                "msResolution": false,
                "shared": true,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
              },
              "yaxes": [
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                },
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                }
              ]
            }
          ],
          "showTitle": false,
          "titleSize": "h6",
          "height": "250px",
          "repeat": null,
          "repeatRowId": null,
          "repeatIteration": null,
          "collapse": false
        }
      ]
    }