apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "influxdb"
  labels:
    app: "influxdb"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "influxdb"
        name: "influxdb"
        app: "influxdb"
    spec:
      containers:
        - name: "influxdb"
          image: "influxdb:1.1.1"
          ports:
            - containerPort: 8083
            - containerPort: 8086
          env:
            - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
              value: "true"
          imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: NodePort
  ports:
  - port: 8086
    protocol: TCP
    nodePort: 30086
    name: external
  - port: 8083
    protocol: TCP
    nodePort: 30083
    name: admin
  selector:
    app: influxdb